networks:
  app_network:

services:
  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"   # opcional para host
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  back:
    build: ./backend
    container_name: back
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:cached      # sincroniza código host ↔ contenedor
      - /app/node_modules    # evita sobrescribir node_modules del contenedor
    environment:
      NODE_ENV: development
      MONGO_URI: mongo://mongo:27017/avstickers
      TEST_MP_ACCESS_TOKEN: ${TEST_MP_ACCESS_TOKEN}
      TEST_MP_PUBLIC_KEY: ${TEST_MP_PUBLIC_KEY}
      PORT: 4000
    depends_on:
      - mongo
    networks:
      - app_network

  front:
    build: ./frontend
    container_name: front
    ports:
      - "5173:5173" # puerto por defecto de Vite
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: http://back:4000   # para que el front se conecte al back
    depends_on:
      - back
    networks:
      - app_network

volumes:
  mongo_data: